name: Pest Tests

on:
  push:
    paths:
      - "**.php"
      - "composer.lock"
  pull_request:
    paths:
      - "**.php"
      - "composer.lock"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install
        run: composer kirby

      - name: PEST
        run: vendor/bin/pest --ci
